"""Shared validated data models."""

from netsage.models.core import (
    HEALTH_DEGRADED_THRESHOLD_PERCENT,
    HEALTH_UNHEALTHY_THRESHOLD_PERCENT,
    VLAN,
    ArpEntry,
    Capability,
    CommandResult,
    CredentialReference,
    DataTrust,
    DeviceFacts,
    DeviceRef,
    FirewallAction,
    FirewallPolicy,
    HealthStatus,
    Interface,
    InterfaceErrors,
    InterfaceState,
    LldpNeighbor,
    MacEntry,
    PingResult,
    Platform,
    Route,
    SystemHealth,
    TracerouteHop,
    TracerouteResult,
)

__all__ = [
    "HEALTH_DEGRADED_THRESHOLD_PERCENT",
    "HEALTH_UNHEALTHY_THRESHOLD_PERCENT",
    "VLAN",
    "ArpEntry",
    "Capability",
    "CommandResult",
    "CredentialReference",
    "DataTrust",
    "DeviceFacts",
    "DeviceRef",
    "FirewallAction",
    "FirewallPolicy",
    "HealthStatus",
    "Interface",
    "InterfaceErrors",
    "InterfaceState",
    "LldpNeighbor",
    "MacEntry",
    "PingResult",
    "Platform",
    "Route",
    "SystemHealth",
    "TracerouteHop",
    "TracerouteResult",
]
